import type { ReactNode } from "react";
import { CalendarCheck, TriangleAlert, Users } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { InfoGrid, MetricCard, QuickActionBar, StatusBadge, SummaryPanel, Timeline, type QuickAction, type TimelineItem } from "../shared";

export type AttendanceState="present"|"late"|"absent"|"excused";
const attendanceTone={present:"success",late:"warning",absent:"danger",excused:"info"} as const;
export function AttendanceStatusBadge({status}:{status:AttendanceState}){return <StatusBadge label={status} tone={attendanceTone[status]}/>;}
export function AttendanceCard({label,value,status,detail}:{label:string;value:string;status:AttendanceState;detail?:string}){return <SummaryPanel title={label} description={detail} action={<AttendanceStatusBadge status={status}/>}><p className="text-3xl font-semibold tabular-nums">{value}</p></SummaryPanel>;}
export function AttendanceSummary({present,late,absent,excused=0}:{present:number;late:number;absent:number;excused?:number}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries({Present:present,Late:late,Absent:absent,Excused:excused}).map(([label,value])=><MetricCard key={label} label={label} value={String(value)}/>)}</div>;}
export function AttendanceTimeline({items}:{items:TimelineItem[]}){return <Timeline items={items} empty="No attendance changes"/>;}
export function AttendanceTrendCard({rate,change}:{rate:number;change:string}){return <SummaryPanel title="Attendance trend" description={change}><p className="text-3xl font-semibold tabular-nums">{rate}%</p><Progress className="mt-4" value={rate}/></SummaryPanel>;}
export function AttendanceRiskIndicator({rate,threshold=90}:{rate:number;threshold?:number}){const risk=rate<threshold;return <div className="flex items-center gap-3 rounded-xl border p-4">{risk?<TriangleAlert className="size-5 text-warning" aria-hidden/>:<CalendarCheck className="size-5 text-success" aria-hidden/>}<div><p className="font-medium">{risk?"Intervention required":"Attendance on track"}</p><p className="text-sm text-muted-foreground">{rate}% · threshold {threshold}%</p></div></div>;}
export function AttendanceExceptionCard({title,description,status="open",action}:{title:string;description:string;status?:"open"|"review"|"resolved";action?:ReactNode}){return <SummaryPanel title={title} description={description} action={<div className="flex items-center gap-2"><StatusBadge label={status} tone={status==="resolved"?"success":status==="review"?"warning":"danger"}/>{action}</div>}><p className="text-sm text-muted-foreground">Requires a recorded resolution before closure.</p></SummaryPanel>;}
export function AttendanceHeatmap({days}:{days:{label:string;value:number}[]}){return <div role="img" aria-label="Attendance heatmap" className="grid grid-cols-7 gap-2">{days.map(d=><div key={d.label} title={`${d.label}: ${d.value}%`} className="aspect-square rounded border p-1 text-center text-xs" style={{backgroundColor:`color-mix(in srgb, var(--success) ${Math.min(100,Math.max(10,d.value))}%, transparent)`}}><span className="sr-only">{d.label}: {d.value}%</span></div>)}</div>;}
export function AttendanceClassWidget({name,marked,total}:{name:string;marked:number;total:number}){return <SummaryPanel title={name} action={<Users className="size-5 text-primary" aria-hidden/>}><InfoGrid items={[{label:"Marked",value:marked},{label:"Total",value:total},{label:"Remaining",value:Math.max(0,total-marked)}]}/></SummaryPanel>;}
export function AttendanceTeacherWidget({name,submitted,pending}:{name:string;submitted:number;pending:number}){return <SummaryPanel title={name} description="Teacher registers"><InfoGrid items={[{label:"Submitted",value:submitted},{label:"Pending",value:pending}]}/></SummaryPanel>;}
export function AttendanceStudentWidget({name,rate,status}:{name:string;rate:string;status:AttendanceState}){return <SummaryPanel title={name} action={<AttendanceStatusBadge status={status}/>}><p className="text-2xl font-semibold">{rate}</p></SummaryPanel>;}
export function AttendanceQuickActionBar({actions}:{actions:QuickAction[]}){return <QuickActionBar actions={actions} label="Attendance quick actions"/>;}
export function AttendanceMetrics({items}:{items:{label:string;value:string;detail?:string}[]}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(x=><MetricCard key={x.label}{...x}/>)}</div>;}
