import type { RoleKey } from './roles.js';
import { Permission, ALL_PERMISSIONS } from './permissions.js';

/**
 * Default role → permission mapping (the system RBAC baseline), derived from the RBAC matrix
 * in docs/architecture/05-rbac-matrix.md. Seeded per tenant during provisioning (Phase 4) and
 * for platform-plane roles during platform setup. `'*'` means "all permissions".
 *
 * Scoped (row-level) restrictions for roles like Teacher/Parent/Student (e.g. only their own
 * sections/children) are enforced in the service/repository layer, not by the permission set.
 */
/**
 * Every platform-plane capability: the whole `platform:*` namespace plus the cross-cutting keys a
 * console operator needs. Deliberately EXCLUDES school-operational permissions — platform employees
 * manage the platform, and reach a specific school only via audited impersonation, never by holding
 * school permissions directly. This keeps platform accounts "console-only".
 */
const PLATFORM_CONSOLE_PERMISSIONS: Permission[] = [
  ...ALL_PERMISSIONS.filter((p) => p.startsWith('platform:')),
  Permission.SUPPORT_IMPERSONATE,
  Permission.AUDIT_READ,
  Permission.FEATUREFLAG_MANAGE,
];

/**
 * Employee self-service (Phase 9): every staff member with a login can view their own HR data and
 * submit their own leave. Spread into each school-staff role so ESS is universally available;
 * row-level scoping (own record only) is enforced in the service layer via the actor→employee link.
 */
const ESS_PERMISSIONS: Permission[] = [Permission.ESS_READ, Permission.ESS_REQUEST];

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, Permission[] | '*'> = {
  // Platform plane — console-only (no school-operational permissions; see above).
  PlatformOwner: PLATFORM_CONSOLE_PERMISSIONS,
  PlatformAdmin: [
    Permission.PLATFORM_TENANT_MANAGE,
    Permission.SUPPORT_IMPERSONATE,
    Permission.AUDIT_READ,
    Permission.FEATUREFLAG_MANAGE,
    // Platform Console
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_SUBSCRIPTION_MANAGE,
    Permission.PLATFORM_PLAN_MANAGE,
    Permission.PLATFORM_UPGRADE_REVIEW,
    Permission.PLATFORM_TRIAL_MANAGE,
    Permission.PLATFORM_BILLING_READ,
    Permission.PLATFORM_BILLING_MANAGE,
    Permission.PLATFORM_COUPON_MANAGE,
    Permission.PLATFORM_FEATURE_OVERRIDE,
    Permission.PLATFORM_FEATUREFLAG_MANAGE,
    Permission.PLATFORM_SUPPORT_MANAGE,
    Permission.PLATFORM_AUDIT_READ,
    Permission.PLATFORM_USER_MANAGE,
    Permission.PLATFORM_SYSTEM_HEALTH_READ,
    Permission.PLATFORM_REVENUE_READ,
  ],
  // Platform Finance: subscriptions, billing, coupons, revenue.
  PlatformFinance: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_SUBSCRIPTION_MANAGE,
    Permission.PLATFORM_UPGRADE_REVIEW,
    Permission.PLATFORM_BILLING_READ,
    Permission.PLATFORM_BILLING_MANAGE,
    Permission.PLATFORM_COUPON_MANAGE,
    Permission.PLATFORM_REVENUE_READ,
    Permission.PLATFORM_AUDIT_READ,
  ],
  // Platform Support: read-mostly + support ops + impersonation + feature overrides for triage.
  PlatformSupport: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_SUPPORT_MANAGE,
    Permission.PLATFORM_FEATURE_OVERRIDE,
    Permission.PLATFORM_AUDIT_READ,
    Permission.PLATFORM_SYSTEM_HEALTH_READ,
    Permission.SUPPORT_IMPERSONATE,
  ],
  // Platform Sales: schools, subscriptions (read), upgrade review, trials, coupons.
  PlatformSales: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_UPGRADE_REVIEW,
    Permission.PLATFORM_TRIAL_MANAGE,
    Permission.PLATFORM_COUPON_MANAGE,
  ],
  // Platform Read Only: full visibility, zero mutation.
  PlatformReadOnly: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_BILLING_READ,
    Permission.PLATFORM_REVENUE_READ,
    Permission.PLATFORM_AUDIT_READ,
    Permission.PLATFORM_SYSTEM_HEALTH_READ,
  ],
  SupportAgent: [Permission.SUPPORT_IMPERSONATE, Permission.AUDIT_READ],

  // School plane
  SchoolAdmin: '*',
  Principal: [
    ...ESS_PERMISSIONS,
    Permission.TEAM_READ,
    Permission.TEAM_APPROVE,
    Permission.CARD_MANAGE,
    Permission.CARD_READ,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.ATTENDANCE_CONFIGURE,
    Permission.SCHOOL_MANAGE,
    Permission.CAMPUS_MANAGE,
    Permission.ACADEMICYEAR_MANAGE,
    Permission.GRADE_MANAGE,
    Permission.SECTION_MANAGE,
    Permission.CLASSROOM_MANAGE,
    Permission.ORGANIZATION_READ,
    // HR oversight: read staff + org, and drive employee lifecycle (but not day-to-day HR editing).
    Permission.EMPLOYEE_READ,
    Permission.HR_SENSITIVE_READ,
    Permission.HR_LIFECYCLE_MANAGE,
    Permission.HR_ORG_READ,
    Permission.HR_CONTRACT_READ,
    Permission.HR_DOCUMENT_READ,
    Permission.DRIVER_READ,
    Permission.STAFF_LEAVE_READ,
    Permission.STAFF_LEAVE_APPROVE,
    Permission.STAFF_ATTENDANCE_READ,
    Permission.PERFORMANCE_READ,
    Permission.PERFORMANCE_MANAGE,
    Permission.TRAINING_READ,
    Permission.ASSET_READ,
    Permission.RECRUITMENT_READ,
    Permission.HR_DASHBOARD_READ,
    Permission.TIMETABLE_READ,
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_READ,
    Permission.ANNOUNCEMENT_MANAGE,
    Permission.NOTIFICATION_SEND,
    Permission.NOTIFICATION_SETTINGS,
    Permission.LEAVE_APPROVE,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
    Permission.AUDIT_READ,
    Permission.FINANCE_READ,
    Permission.SUBSCRIPTION_READ,
    Permission.SUBSCRIPTION_UPGRADE_REQUEST,
    Permission.DOCUMENT_READ,
    Permission.RESOURCE_READ,
    Permission.RESOURCE_MANAGE,
    Permission.ACHIEVEMENT_MANAGE,
    Permission.BUS_READ,
    Permission.LIBRARY_READ,
    Permission.INVENTORY_READ,
    Permission.CLINIC_READ,
  ],
  VicePrincipal: [
    ...ESS_PERMISSIONS,
    Permission.TEAM_READ,
    Permission.TEAM_APPROVE,
    Permission.CARD_READ,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.EMPLOYEE_READ,
    Permission.HR_ORG_READ,
    Permission.STAFF_LEAVE_READ,
    Permission.STAFF_LEAVE_APPROVE,
    Permission.STAFF_ATTENDANCE_READ,
    Permission.PERFORMANCE_READ,
    Permission.PERFORMANCE_MANAGE,
    Permission.TRAINING_READ,
    Permission.HR_DASHBOARD_READ,
    Permission.ATTENDANCE_CONFIGURE,
    Permission.TIMETABLE_MANAGE,
    Permission.ATTENDANCE_CREATE,
    Permission.ATTENDANCE_READ,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.HOMEWORK_READ,
    Permission.GRADE_READ,
    Permission.ANNOUNCEMENT_MANAGE,
    Permission.NOTIFICATION_SEND,
    Permission.LEAVE_APPROVE,
    Permission.PTM_MANAGE,
    Permission.REPORT_READ,
    Permission.RESOURCE_READ,
    Permission.RESOURCE_MANAGE,
    Permission.ACHIEVEMENT_MANAGE,
  ],
  FinanceOfficer: [
    ...ESS_PERMISSIONS,
    Permission.FINANCE_MANAGE,
    Permission.FINANCE_READ,
    Permission.FINANCE_EXPORT,
    Permission.FINANCE_TRANSFER_BILLING, // manager-level: change the legal payer
    // Payroll preparation consumes staff attendance + approved leave (read-only source).
    Permission.STAFF_ATTENDANCE_READ,
    Permission.PAYROLL_PREPARE,

    Permission.TRANSACTION_CREATE,
    Permission.RECEIPT_UPLOAD,
    Permission.ENROLLMENT_MANAGE,
    Permission.FEE_OVERRIDE,
    Permission.FINANCE_APPROVE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_GENERATE,
    Permission.DOCUMENT_UPLOAD_SIGNED,
    Permission.DOCUMENT_REPLACE_SIGNED,
    Permission.DOCUMENT_DELETE_SIGNED,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
    Permission.AUDIT_READ,
  ],
  // Accountant: finance operations + can register students (per product requirement).
  Accountant: [
    ...ESS_PERMISSIONS,
    Permission.FINANCE_MANAGE,
    Permission.FINANCE_READ,
    Permission.FINANCE_EXPORT,
    Permission.TRANSACTION_CREATE,
    Permission.RECEIPT_UPLOAD,
    Permission.STUDENT_MANAGE,
    Permission.ENROLLMENT_MANAGE,
    Permission.FEE_OVERRIDE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_GENERATE,
    Permission.DOCUMENT_UPLOAD_SIGNED,
    Permission.DOCUMENT_REPLACE_SIGNED,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
  ],
  Teacher: [
    ...ESS_PERMISSIONS,
    Permission.CARD_READ,
    Permission.PRESENCE_CREATE,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_CREATE,
    Permission.TRANSPORT_READ,
    Permission.TIMETABLE_READ,
    Permission.ATTENDANCE_CREATE,
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_MANAGE,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_IMPORT,
    Permission.GRADE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.NOTIFICATION_SEND,
    Permission.REPORT_READ,
    Permission.RESOURCE_READ,
    Permission.RESOURCE_MANAGE,
    Permission.ACHIEVEMENT_MANAGE,
  ],
  Secretary: [
    ...ESS_PERMISSIONS,
    Permission.CARD_MANAGE,
    Permission.CARD_READ,
    Permission.PRESENCE_CREATE,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.STUDENT_MANAGE,
    Permission.PARENT_MANAGE,
    Permission.DOCUMENT_MANAGE,
    Permission.ATTENDANCE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.TIMETABLE_READ,
    // Advanced modules operations (gated by per-tenant feature flags)
    Permission.BUS_MANAGE,
    Permission.BUS_ASSIGN,
    Permission.BUS_READ,
    Permission.LIBRARY_MANAGE,
    Permission.LIBRARY_READ,
    Permission.INVENTORY_MANAGE,
    Permission.INVENTORY_READ,
    Permission.CLINIC_MANAGE,
    Permission.CLINIC_READ,
  ],
  // Receptionist: front-desk — sends announcements/notifications, reads attendance, manages docs.
  Receptionist: [
    ...ESS_PERMISSIONS,
    Permission.PRESENCE_CREATE,
    Permission.PRESENCE_READ,
    Permission.ANNOUNCEMENT_MANAGE,
    Permission.NOTIFICATION_SEND,
    Permission.ATTENDANCE_READ,
    Permission.CARD_READ,
    Permission.DOCUMENT_MANAGE,
  ],
  // Registrar: student/parent records, admissions, quotations and fee overrides.
  Registrar: [
    ...ESS_PERMISSIONS,
    Permission.STUDENT_MANAGE,
    Permission.PARENT_MANAGE,
    Permission.DOCUMENT_MANAGE,
    Permission.ENROLLMENT_MANAGE,
    Permission.FEE_OVERRIDE,
    Permission.FINANCE_READ,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_GENERATE,
    Permission.DOCUMENT_UPLOAD_SIGNED,
    Permission.DOCUMENT_REPLACE_SIGNED,
    Permission.DOCUMENT_DELETE_SIGNED,
    Permission.REPORT_READ,
  ],
  // Counselor: behaviour & achievements, reads attendance.
  Counselor: [
    ...ESS_PERMISSIONS,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.ATTENDANCE_READ,
    Permission.ACHIEVEMENT_MANAGE,
  ],
  // HR: full staff records, lifecycle, org structure & leave approvals.
  HR: [
    ...ESS_PERMISSIONS,
    Permission.TEAM_READ,
    Permission.TEAM_APPROVE,
    Permission.EMPLOYEE_READ,
    Permission.EMPLOYEE_MANAGE,
    Permission.HR_SENSITIVE_READ,
    Permission.HR_LIFECYCLE_MANAGE,
    Permission.HR_ORG_READ,
    Permission.HR_ORG_MANAGE,
    Permission.HR_CONTRACT_READ,
    Permission.HR_CONTRACT_MANAGE,
    Permission.HR_DOCUMENT_READ,
    Permission.HR_DOCUMENT_MANAGE,
    Permission.DRIVER_READ,
    Permission.DRIVER_MANAGE,
    Permission.STAFF_LEAVE_READ,
    Permission.STAFF_LEAVE_REQUEST,
    Permission.STAFF_LEAVE_APPROVE,
    Permission.STAFF_LEAVE_MANAGE,
    Permission.STAFF_ATTENDANCE_READ,
    Permission.STAFF_ATTENDANCE_MANAGE,
    Permission.PAYROLL_PREPARE,
    Permission.SHIFT_READ,
    Permission.SHIFT_MANAGE,
    Permission.ATTENDANCE_POLICY_READ,
    Permission.ATTENDANCE_POLICY_MANAGE,
    Permission.ATTENDANCE_LOCK_MANAGE,
    Permission.ATTENDANCE_CORRECTION_REQUEST,
    Permission.ATTENDANCE_CORRECTION_APPROVE,
    Permission.BIOMETRIC_INGEST,
    Permission.PERFORMANCE_READ,
    Permission.PERFORMANCE_MANAGE,
    Permission.TRAINING_READ,
    Permission.TRAINING_MANAGE,
    Permission.ASSET_READ,
    Permission.ASSET_MANAGE,
    Permission.RECRUITMENT_READ,
    Permission.RECRUITMENT_MANAGE,
    Permission.HR_DASHBOARD_READ,
    Permission.TEACHER_MANAGE,
    Permission.LEAVE_APPROVE,
  ],
  // Nurse: clinic module + attendance visibility.
  Nurse: [
    ...ESS_PERMISSIONS,
    Permission.CLINIC_MANAGE,
    Permission.CLINIC_READ,
    Permission.ATTENDANCE_READ,
  ],
  // Librarian: library module.
  Librarian: [...ESS_PERMISSIONS, Permission.LIBRARY_MANAGE, Permission.LIBRARY_READ],
  // StoreKeeper: inventory module.
  StoreKeeper: [...ESS_PERMISSIONS, Permission.INVENTORY_MANAGE, Permission.INVENTORY_READ],
  // FleetAdmin: configures buses/routes and assigns students (gated by bus_tracking).
  FleetAdmin: [
    ...ESS_PERMISSIONS,
    Permission.BUS_MANAGE,
    Permission.BUS_ASSIGN,
    Permission.BUS_READ,
    Permission.TRANSPORT_READ,
    Permission.CARD_READ,
    Permission.EMPLOYEE_READ,
    Permission.DRIVER_READ,
    Permission.DRIVER_MANAGE,
  ],
  // BusSupervisor: on-board boarding/alighting scans.
  BusSupervisor: [
    ...ESS_PERMISSIONS,
    Permission.TRANSPORT_CREATE,
    Permission.TRANSPORT_READ,
    Permission.CARD_READ,
    Permission.BUS_READ,
    Permission.PRESENCE_READ,
    Permission.DRIVER_READ,
  ],
  Parent: [
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_READ,
    Permission.TIMETABLE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.RECEIPT_UPLOAD,
    Permission.FINANCE_READ,
    Permission.LEAVE_REQUEST,
    Permission.PTM_BOOK,
    Permission.DOCUMENT_MANAGE,
    Permission.RESOURCE_READ,
    Permission.ACHIEVEMENT_READ,
    Permission.GAMIFICATION_READ,
  ],
  Student: [
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_READ,
    Permission.TIMETABLE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.RESOURCE_READ,
    Permission.ACHIEVEMENT_READ,
    Permission.GAMIFICATION_READ,
  ],
};

/** Resolve the concrete permission set for a role (expanding `'*'`). */
export function permissionsForRole(role: RoleKey): Permission[] {
  const mapped = DEFAULT_ROLE_PERMISSIONS[role];
  return mapped === '*' ? [...ALL_PERMISSIONS] : mapped;
}
