import { Banknote, BookOpenCheck, Bus, CalendarCheck, CircleDollarSign, ClipboardCheck, FileChartColumn, GraduationCap, School, TrendingUp, UserCheck, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DashboardTemplate, type DashboardMetric } from "./DashboardTemplate";

const List = ({ items }: { items: string[] }) => <ul className="space-y-3 text-sm">{items.map((item) => <li key={item} className="rounded-lg border p-3">{item}</li>)}</ul>;
const Placeholder = ({ label }: { label: string }) => <div className="flex min-h-56 items-center justify-center rounded-lg border border-dashed bg-muted/30 text-sm text-muted-foreground">{label}</div>;
function makeTemplate(eyebrow: string, title: string, description: string, metrics: DashboardMetric[], overview: string, attention: string[]) {
  return function Template() { return <DashboardTemplate eyebrow={eyebrow} title={title} description={description} metrics={metrics} primary={<Placeholder label={overview} />} secondary={<List items={attention} />} actions={<Button>View report</Button>} />; };
}
export const PrincipalDashboard = makeTemplate("School overview", "Principal dashboard", "A decision layer for academic, financial, and operational health.", [{label:"Students",value:"1,842",change:"2.4% this term",icon:GraduationCap},{label:"Attendance",value:"94.7%",change:"0.8% this week",icon:CalendarCheck},{label:"Fee collection",value:"91%",change:"3.1% this month",icon:CircleDollarSign},{label:"Open actions",value:"12",icon:ClipboardCheck}], "Enrollment and attendance trend", ["18 students below attendance threshold", "Three approvals are awaiting review"]);
export const FinanceDashboard = makeTemplate("Finance", "Finance dashboard", "Collections, cash position, aging, and exceptions in one view.", [{label:"Collected",value:"$1.42m",change:"8% vs target",icon:Banknote},{label:"Outstanding",value:"$128k",icon:CircleDollarSign},{label:"Collection rate",value:"91%",icon:TrendingUp},{label:"Overdue accounts",value:"47",icon:Users}], "Collection performance", ["Nine accounts overdue by 60+ days", "Reconciliation variance requires review"]);
export const AttendanceDashboard = makeTemplate("Operations", "Attendance dashboard", "Live attendance health with intervention-ready exceptions.", [{label:"Present",value:"1,746",icon:UserCheck},{label:"Absent",value:"64",icon:Users},{label:"Late",value:"32",icon:CalendarCheck},{label:"Buses checked",value:"18/20",icon:Bus}], "Attendance by grade", ["Grade 8B is below the weekly threshold", "Two transport registers are incomplete"]);
export const TeacherDashboard = makeTemplate("My classes", "Teacher dashboard", "Today’s classes, student signals, and grading workload.", [{label:"Classes today",value:"5",icon:School},{label:"Students",value:"126",icon:Users},{label:"To grade",value:"18",icon:BookOpenCheck},{label:"Attendance due",value:"2",icon:ClipboardCheck}], "Class performance", ["Submit attendance for Grade 6A", "Four assignments need feedback"]);
export const ReportsDashboard = makeTemplate("Analytics", "Reports dashboard", "Trusted reporting with ownership, freshness, and export state.", [{label:"Saved reports",value:"24",icon:FileChartColumn},{label:"Scheduled",value:"7",icon:CalendarCheck},{label:"Shared",value:"11",icon:Users},{label:"Updated today",value:"8",icon:TrendingUp}], "Report activity", ["Two scheduled reports failed", "Enrollment report needs an owner"]);
