import { useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import { Search, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AuditTrail, IdentityHeader, MetricCard, StatusBadge, Timeline, type TimelineItem } from "@/domain-components/shared";

export interface WorkspaceTab { id:string; label:string; content:ReactNode }
export interface WorkspaceMetric { label:string; value:string; detail?:string; icon?:ReactNode }
export interface RelatedRecord { id:string; type:string; label:string; detail?:string; status?:ReactNode; onOpen?:()=>void }
export interface WorkspaceAction { id:string; label:string; kind?:"primary"|"secondary"|"danger"|"approval"; onSelect?:()=>void; disabled?:boolean; disabledReason?:string }

export function ActionPanel({actions}:{actions:WorkspaceAction[]}){const primary=actions.filter(a=>a.kind==="primary"||a.kind==="approval");const others=actions.filter(a=>a.kind!=="primary"&&a.kind!=="approval");return <Card><CardHeader><CardTitle>Actions</CardTitle></CardHeader><CardContent className="space-y-2">{[...primary,...others].map(a=><div key={a.id}><Button className="w-full justify-start" variant={a.kind==="primary"?"default":a.kind==="danger"?"destructive":"outline"} onClick={a.onSelect} disabled={a.disabled}>{a.label}</Button>{a.disabled&&a.disabledReason&&<p className="mt-1 text-xs text-muted-foreground">{a.disabledReason}</p>}</div>)}</CardContent></Card>;}

export function RelatedRecords({records,view="cards",title="Related records"}:{records:RelatedRecord[];view?:"cards"|"table";title?:string}){
  if(view==="table")return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Record</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Action</span></TableHead></TableRow></TableHeader><TableBody>{records.map(r=><TableRow key={r.id}><TableCell><p className="font-medium">{r.label}</p><p className="text-xs text-muted-foreground">{r.detail}</p></TableCell><TableCell>{r.type}</TableCell><TableCell>{r.status}</TableCell><TableCell className="text-end">{r.onOpen&&<Button size="sm" variant="ghost" onClick={r.onOpen} aria-label={`Open ${r.label}`}>Open</Button>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>;
  return <section aria-labelledby="related-title"><h2 id="related-title" className="mb-4 text-xl font-semibold">{title}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{records.map(r=><Card key={r.id}><CardContent className="pt-0"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{r.type}</p><h3 className="mt-1 font-semibold">{r.label}</h3><p className="mt-1 text-sm text-muted-foreground">{r.detail}</p></div>{r.status}</div>{r.onOpen&&<Button className="mt-4" size="sm" variant="outline" onClick={r.onOpen}>Open record</Button>}</CardContent></Card>)}</div></section>;
}

export function RecordTimeline({items}:{items:TimelineItem[]}){return <Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent><Timeline items={items} empty="No record history"/></CardContent></Card>;}
export function RecordAuditTrail({items}:{items:TimelineItem[]}){return <Card><CardHeader><CardTitle>Audit trail</CardTitle></CardHeader><CardContent><AuditTrail items={items}/></CardContent></Card>;}

export function RecordWorkspace({name,subtitle,status,headerActions,metrics,tabs,related,timeline,audit,actions}:{name:string;subtitle:string;status?:ReactNode;headerActions?:ReactNode;metrics:WorkspaceMetric[];tabs:WorkspaceTab[];related:RelatedRecord[];timeline:TimelineItem[];audit:TimelineItem[];actions:WorkspaceAction[]}){
  return <div className="space-y-6"><IdentityHeader name={name} subtitle={subtitle} status={status} actions={headerActions}/><section aria-label="Summary metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.slice(0,4).map(m=><MetricCard key={m.label}{...m}/>)}</section><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_18rem]"><div className="min-w-0 space-y-6"><Tabs defaultValue={tabs[0]?.id}><TabsList className="flex h-auto flex-wrap justify-start">{tabs.map(t=><TabsTrigger key={t.id} value={t.id}>{t.label}</TabsTrigger>)}</TabsList>{tabs.map(t=><TabsContent key={t.id} value={t.id} className="mt-5">{t.content}</TabsContent>)}</Tabs><RelatedRecords records={related}/><RecordTimeline items={timeline}/><RecordAuditTrail items={audit}/></div><aside aria-label="Record actions"><ActionPanel actions={actions}/></aside></div></div>;
}

export interface SearchResult { id:string; type:string; label:string; detail:string; status?:string; onOpen?:()=>void }
export function UniversalSearch({results,query,onQueryChange,recent=[]}:{results:SearchResult[];query:string;onQueryChange?:(value:string)=>void;recent?:string[]}){
  const [active,setActive]=useState(0);
  const optionRefs=useRef<Array<HTMLButtonElement|null>>([]);
  const move=(event:KeyboardEvent,delta:number)=>{if(!results.length)return;event.preventDefault();const next=(active+delta+results.length)%results.length;setActive(next);optionRefs.current[next]?.focus();};
  return <div className="space-y-4" onKeyDown={event=>{if(event.key==="ArrowDown")move(event,1);if(event.key==="ArrowUp")move(event,-1);}}><label className="relative block"><span className="sr-only">Search records</span><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden/><Input className="ps-9" value={query} onChange={e=>{setActive(0);onQueryChange?.(e.target.value)}} placeholder="Search students, teachers, parents, invoices, attendance…"/></label>{!query&&recent.length>0&&<div><h3 className="text-sm font-medium">Recent searches</h3><div className="mt-2 flex flex-wrap gap-2">{recent.map(x=><Button key={x} size="sm" variant="outline" onClick={()=>onQueryChange?.(x)}>{x}</Button>)}</div></div>}<div role="listbox" aria-label="Search results" className="divide-y rounded-xl border bg-card">{results.map((r,index)=><button ref={node=>{optionRefs.current[index]=node}} role="option" aria-selected={index===active} tabIndex={index===active?0:-1} key={r.id} onFocus={()=>setActive(index)} onClick={r.onOpen} className="flex w-full items-center gap-3 p-4 text-start hover:bg-muted focus:bg-muted"><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">{r.type}</p><p className="truncate font-medium">{r.label}</p><p className="truncate text-sm text-muted-foreground">{r.detail}</p></div>{r.status&&<StatusBadge label={r.status} tone="neutral"/>}</button>)}{query&&results.length===0&&<p className="p-6 text-center text-sm text-muted-foreground">No authorized records match this search.</p>}</div></div>;
}

export function PermissionBoundary({mode="denied",reason}:{mode?:"denied"|"read-only"|"approval";reason:string}){return <div role="status" className="flex gap-3 rounded-xl border bg-muted/20 p-5"><ShieldAlert className="size-5 text-warning" aria-hidden/><div><p className="font-medium">{mode==="denied"?"Access unavailable":mode==="read-only"?"Read only":"Approval required"}</p><p className="mt-1 text-sm text-muted-foreground">{reason}</p></div></div>;}
