export type Pattern = { id: string; title: string; description: string; diagram: string[]; usage: string[]; do: string[]; dont: string[]; example: string; };
export const patterns: Pattern[] = [
  { id:"dashboard", title:"Dashboard Pattern", description:"A role-based decision surface that prioritizes signals, trends, and actions over raw data.", diagram:["Context + actions","Key metrics","Primary analysis | Exceptions","Recent activity"], usage:["Choose metrics tied to the role's decisions.","Show data freshness and scope.","Place exceptions beside the analysis they explain."], do:["Use four or fewer top-level metrics.","Make the next action explicit."], dont:["Turn every value into a card.","Use decorative charts without decisions."], example:"A principal sees attendance risk, fee collection, and approval exceptions for the active school." },
  { id:"crud", title:"CRUD Pattern", description:"A predictable list-detail workflow for high-volume operational records.", diagram:["Title + create action","Search + filters + saved view","Data table","Pagination / bulk action"], usage:["Keep create as the single primary action.","Persist filters in the URL.","Use a side panel only for brief review or edits."], do:["Confirm destructive actions.","Preserve selection after reversible updates."], dont:["Hide filters in unrelated menus.","Open every record in a modal."], example:"Admissions staff filter applicants by stage, select records, and assign an interviewer." },
  { id:"student-profile", title:"Student Profile Pattern", description:"A durable student record with identity, status, relationships, and task-focused sections.", diagram:["Identity + status + actions","Summary signals","Overview | Attendance | Finance | Documents","Section content"], usage:["Keep identity visible while navigating.","Show sensitive data according to permissions.","Use tabs for stable domains, not single actions."], do:["Surface guardians and enrollment status.","Show effective dates."], dont:["Repeat identity in every section.","Mix academic and financial permissions."], example:"A registrar reviews enrollment, guardians, documents, and contact history without losing student context." },
  { id:"attendance", title:"Attendance Pattern", description:"A fast, auditable workflow for marking attendance and resolving exceptions.", diagram:["Date + class context","Progress + bulk actions","Student roster + status","Submit + audit state"], usage:["Default to the most likely status only when policy allows.","Support keyboard status entry.","Separate saving a draft from submission."], do:["Announce status changes to assistive technology.","Keep absent reasons structured."], dont:["Use color as the only status cue.","Submit silently."], example:"A teacher marks a class using P/L/A shortcuts, records absence reasons, then submits the register." },
  { id:"finance", title:"Finance Pattern", description:"A traceable financial view for balances, transactions, collections, and exceptions.", diagram:["Account scope + period","Balance + collection metrics","Trend / aging","Transactions + reconciliation"], usage:["Use tabular numbers and explicit currency.","Show posting and settlement state.","Gate refunds and write-offs by permission."], do:["Display totals with their period.","Keep an immutable audit trail."], dont:["Mix forecast and actual without labels.","Rely on red/green alone."], example:"A finance officer reviews family balances, records a payment, and exports an aging report." },
  { id:"reports", title:"Reports Pattern", description:"A trustworthy reporting workflow with clear parameters, freshness, and sharing controls.", diagram:["Report title + owner","Parameters + run","Results summary","Table / chart + export"], usage:["Expose last updated time and data scope.","Validate parameters before running.","Preserve a printable table alternative."], do:["Name reports by decision or question.","Make exports asynchronous when large."], dont:["Auto-run expensive reports.","Show truncated totals."], example:"An operations lead runs transport utilization by campus and schedules a monthly PDF." },
  { id:"settings", title:"Settings Pattern", description:"A low-frequency configuration surface organized by ownership and consequence.", diagram:["Settings navigation","Section title + description","Grouped fields","Save state"], usage:["Group by user mental model, not database entity.","Explain downstream effects.","Use autosave only for low-risk preferences."], do:["Show unsaved state.","Require reauthentication for sensitive changes."], dont:["Mix personal and organization settings.","Use a single endless form."], example:"An administrator configures attendance thresholds with a preview of affected workflows." },
  { id:"empty", title:"Empty States", description:"A contextual explanation when no records or results are available.", diagram:["Optional icon","Clear state title","Reason + next step","Primary action"], usage:["Distinguish first-use, no-results, and permission states.","Keep actions relevant to the user's role."], do:["Explain how to create or find data.","Preserve active filter context."], dont:["Use celebratory copy for errors.","Show an illustration without guidance."], example:"No applicants match these filters; clear stage filters or create an application." },
  { id:"loading", title:"Loading States", description:"Progress feedback that preserves layout and prevents duplicate actions.", diagram:["Stable page chrome","Skeleton matching content","Optional progress label"], usage:["Use skeletons for predictable layouts.","Use progress for measurable operations.","Announce long-running changes."], do:["Keep navigation interactive.","Respect reduced motion."], dont:["Show a full-page spinner for local updates.","Fake precise progress."], example:"The student table retains headers and filter controls while rows render as skeletons." },
  { id:"error", title:"Error States", description:"Recoverable, specific failure feedback with retained user input and support context.", diagram:["What failed","Impact in plain language","Retry / alternate action","Reference ID"], usage:["Place validation errors by the field.","Use a page error only when the page cannot function.","Log technical details outside user copy."], do:["Preserve entered values.","Provide a retry when safe."], dont:["Expose stack traces.","Blame the user."], example:"Payment recording failed; the draft is retained and can be retried with reference FIN-2041." },
];
