import type { ReactNode } from "react";
import { Banknote, CreditCard, ReceiptText, WalletCards } from "lucide-react";
import { InfoGrid, MetricCard, QuickActionBar, StatusBadge, SummaryPanel, Timeline, type QuickAction, type TimelineItem } from "../shared";

export type FinanceState="paid"|"partial"|"due"|"overdue"|"pending"|"failed"|"refunded";
const financeTone:Record<FinanceState,"success"|"warning"|"info"|"danger"|"neutral">={paid:"success",partial:"warning",due:"info",overdue:"danger",pending:"warning",failed:"danger",refunded:"neutral"};
export function FinanceStatusBadge({status}:{status:FinanceState}){return <StatusBadge label={status} tone={financeTone[status]}/>;}
export function BalanceCard({balance,label="Outstanding balance",detail}:{balance:string;label?:string;detail?:string}){return <MetricCard label={label} value={balance} detail={detail} icon={<WalletCards className="size-4" aria-hidden/>}/>}
export function InvoiceCard({number,amount,dueDate,status}:{number:string;amount:string;dueDate:string;status:FinanceState}){return <SummaryPanel title={number} description={`Due ${dueDate}`} action={<FinanceStatusBadge status={status}/>}><p className="text-2xl font-semibold tabular-nums">{amount}</p></SummaryPanel>;}
export function PaymentCard({reference,amount,method,status}:{reference:string;amount:string;method:string;status:FinanceState}){return <SummaryPanel title={reference} description={method} action={<FinanceStatusBadge status={status}/>}><p className="text-2xl font-semibold tabular-nums">{amount}</p></SummaryPanel>;}
export function ReceiptCard({number,amount,date,onDownload}:{number:string;amount:string;date:string;onDownload?:()=>void}){return <SummaryPanel title={number} description={date} action={<ReceiptText className="size-5 text-primary" aria-hidden/>}><p className="text-2xl font-semibold">{amount}</p>{onDownload&&<button className="mt-3 text-sm font-medium text-primary" onClick={onDownload}>Download receipt</button>}</SummaryPanel>;}
export function CollectionSummary({collected,billed,rate}:{collected:string;billed:string;rate:string}){return <SummaryPanel title="Collection summary" action={<Banknote className="size-5 text-primary" aria-hidden/>}><InfoGrid items={[{label:"Collected",value:collected},{label:"Billed",value:billed},{label:"Rate",value:rate}]}/></SummaryPanel>;}
export function FeeStatusCard({title,amount,paid,status}:{title:string;amount:string;paid:string;status:FinanceState}){return <SummaryPanel title={title} action={<FinanceStatusBadge status={status}/>}><InfoGrid items={[{label:"Amount",value:amount},{label:"Paid",value:paid}]}/></SummaryPanel>;}
export function AgingCard({current,days30,days60,days90}:{current:string;days30:string;days60:string;days90:string}){return <SummaryPanel title="Receivables aging"><InfoGrid columns={4} items={[{label:"Current",value:current},{label:"30 days",value:days30},{label:"60 days",value:days60},{label:"90+ days",value:days90}]}/></SummaryPanel>;}
export function FinanceMetrics({items}:{items:{label:string;value:string;detail?:string}[]}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(x=><MetricCard key={x.label}{...x}/>)}</div>;}
export function OutstandingBalanceCard({balance,overdue,accounts}:{balance:string;overdue:string;accounts:number}){return <SummaryPanel title="Outstanding balances"><InfoGrid items={[{label:"Total",value:balance},{label:"Overdue",value:overdue},{label:"Accounts",value:accounts}]}/></SummaryPanel>;}
export function PaymentMethodCard({label,detail,defaultMethod=false}:{label:string;detail:string;defaultMethod?:boolean}){return <SummaryPanel title={label} description={detail} action={defaultMethod?<StatusBadge label="Default" tone="primary"/>:<CreditCard className="size-5 text-muted-foreground" aria-hidden/>}><span className="text-sm text-muted-foreground">Verified payment method</span></SummaryPanel>;}
export function TransactionTimeline({items}:{items:TimelineItem[]}){return <Timeline items={items} empty="No transactions"/>;}
export function FinanceQuickActions({actions}:{actions:QuickAction[]}){return <QuickActionBar actions={actions} label="Finance quick actions"/>;}

